services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
  app_1:
    image: golang:1.16-alpine
    build: app
    ports:
      - "8081:8081"